class AddAutoGeneratedToHrbpUserManagedDepartment < ActiveRecord::Migration[7.1]
  def change
    add_column :hrbp_user_managed_departments, :auto_generated, :boolean, null: false, default: true
  end
end
